### PR TITLE
fix OnUnitEnterLeave

### PR DESCRIPTION
**Pull request by BlueSaint**

### CODE REVIEW

**Comment by peq** [comment]
Removing the nullTimer is not really a good solution I think.

Before the change you could register the event and have it called for units already on the map because of the nulltimer. Now GroupEnumUnitsInRect will be called before anyone was able to register a callback, so it becomes useless.

That's why I suggested keeping a group of units currently on the map.

**Comment by Frotty** [comment]
and maybe squash the commits to one

**Comment by peq** [comment]
Squashing is not necessary. I can squash them when accepting the request.

**Comment by peq** [comment]
Merged other branch.

**Pull request closed without merging**
